import assert from 'node:assert/strict';
import {appendTitleIndicator,rendererSlot} from '../RainClient/src/plugins/platformindicators/rowIndicators.js';
const clone=(node,props)=>({...node,props:{...node.props,...props}});
const text=Object.freeze({type:'Text',props:Object.freeze({variant:'redesign/channel-title/semibold',children:'Name'})});
const avatar={type:'Avatar',props:{user:{id:'42'}}};
const tree=Object.freeze({type:'View',key:'row',props:Object.freeze({onPress:()=>{},children:Object.freeze([avatar,text])})});
const icon={type:'View',key:'platforms',props:{userId:'42'}};
const result=appendTitleIndicator(tree,n=>n===text,icon,clone);
assert.deepEqual(result.props.children,[avatar,text,icon]);assert.equal(result.props.onPress,tree.props.onPress);assert.equal(tree.props.children.length,2);assert.equal(result.key,'row');
assert.equal(appendTitleIndicator(result,n=>n===text,icon,clone),result);
const styled={type:()=>{},props:{userId:'42',userName:'Styled'}};
const nested={type:'View',props:{children:{type:'View',props:{children:styled}}}};
const out=appendTitleIndicator(nested,n=>n.props.userId==='42'&&'userName' in n.props,icon,clone);
assert.deepEqual(out.props.children.props.children,[styled,icon]);assert.equal(nested.props.children.props.children,styled);
const header={type:()=>{},props:{userId:'42',accessibleTitle:'Name',subtitle:'Status'}};
assert.deepEqual(appendTitleIndicator({type:'View',props:{children:[avatar,header]}},n=>'accessibleTitle' in n.props,icon,clone).props.children,[avatar,header,icon]);
assert.equal(appendTitleIndicator(tree,()=>false,icon,clone),tree);
assert.equal(appendTitleIndicator(text,()=>true,icon,clone),text);
assert.equal(appendTitleIndicator(null,()=>true,icon,clone),null);
const fn=()=>{},memo={type:fn},forward={type:{render:fn}};
assert.deepEqual(rendererSlot(memo),[memo,'type']);assert.deepEqual(rendererSlot(forward),[forward.type,'render']);assert.equal(rendererSlot(undefined),undefined);
console.log('PASS: frozen DM/header trees, styled titles, null/missing nodes, duplicate prevention, callback preservation, memo/forwardRef slots');

const name={type:()=>{},props:{userId:'42',userName:'Name',variant:'heading-xl/bold'}};
const onPress=()=>{};
const profile=Object.freeze({type:'Pressable',props:Object.freeze({onPress,style:{marginTop:4},children:Object.freeze([name])})});
const updated=appendTitleIndicator(profile,n=>n.props.userId==='42'&&'userName' in n.props,icon,clone,{flexDirection:'row',alignItems:'center'});
assert.deepEqual(updated.props.children,[name,icon]);assert.equal(updated.props.onPress,onPress);assert.equal(profile.props.children.length,1);assert.equal(updated.props.style[0],profile.props.style);
console.log('PASS: actual v348 profile styled-name props, heading variant, frozen Pressable, click handler and original style preserved');
